language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - boost-latest
    - kalakris-cmake
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6
    - cmake
    - doxygen
    - gcc-4.8
    - g++-4.8
    - libboost-filesystem1.55-dev
    - libboost-log1.55-dev
    - libboost-program-options1.55-dev
    - libboost-serialization1.55-dev
    - libboost-system1.55-dev
    - libboost-test1.55-dev
    - libboost-thread1.55-dev
    - libboost1.55-dev
    - libibverbs-dev
    - libpci-dev
    - librdmacm-dev
    - libzmq3-dev

before_script:
  - contrib/merge-dependencies
  - mkdir build && cd build
  
script:
  - cmake ..
  - make
  - make test

sudo: false
