before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get -qq update
  - sudo apt-get -y install libboost1.55-dev libboost-filesystem1.55-dev libboost-program-options1.55-dev libboost-serialization1.55-dev libboost-system1.55-dev libboost-test1.55-dev libboost-thread1.55-dev libzmq3-dev
  - sudo wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp -O /usr/local/include/zmq.hpp

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
compiler: clang

language: cpp

script:
  - make
  - make test
