language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - boost-latest
    - kalakris-cmake
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6
    - cmake
    - doxygen
    - gcc-4.8
    - g++-4.8
    - libboost-filesystem1.55-dev
    - libboost-log1.55-dev
    - libboost-program-options1.55-dev
    - libboost-serialization1.55-dev
    - libboost-system1.55-dev
    - libboost-test1.55-dev
    - libboost-thread1.55-dev
    - libboost1.55-dev
    - libibverbs-dev
    - libnuma-dev
    - libpci-dev
    - librdmacm-dev
    - libzmq3-dev
    - valgrind

before_script:
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - contrib/merge-dependencies
  - mkdir build && cd build
  
script:
  - cmake ..
  - make
  - make CTEST_OUTPUT_ON_FAILURE=1 test

after_success:
  - if [ "$CXX" = "g++" ]; then cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && make -j4 && make coveralls; fi

sudo: false
