addons:
  apt:
    sources:
    - boost-latest/ppa
    packages:
    - libboost-filesystem1.55-dev
    - libboost-log1.55-dev
    - libboost-program-options1.55-dev
    - libboost-serialization1.55-dev
    - libboost-system1.55-dev
    - libboost-test1.55-dev
    - libboost-thread1.55-dev
    - libboost1.55-dev
    - libzmq3-dev

before_install:
  - sudo wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp -O /usr/local/include/zmq.hpp

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
compiler: clang

language: cpp

script:
  - make
  - make test
