addons:
  apt:
    sources:
    - boost-latest
    - kalakris-cmake
    packages:
    - cmake
    - doxygen
    - libboost-filesystem1.55-dev
    - libboost-log1.55-dev
    - libboost-program-options1.55-dev
    - libboost-serialization1.55-dev
    - libboost-system1.55-dev
    - libboost-test1.55-dev
    - libboost-thread1.55-dev
    - libboost1.55-dev
    - libibverbs-dev
    - libpci-dev
    - librdmacm-dev
    - libzmq3-dev

before_install:
  - contrib/merge-dependencies

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
compiler: clang

language: cpp

script:
  - make
  - make test

sudo: false
